version: "3"

services:
  web:
    build: .
    command: python leadmanager/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: "localhost"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      ports: 5555:5555
